name: Build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x, 21.x]
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm ci
            - name: Mocha
              run: npm exec mocha -- --exit --require ./babel-register "test/**/*.spec.mjs"
            - name: Build
              run: npm run --if-present build
            - name: Selftest
              run: npm run --if-present selftest
            - name: Integration test
              if: matrix.node-version == '20.x'
              env:
                  WAIT_ON_TIMEOUT: 5000
              run: npm run vite

    vite:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                vite-version: [4.x, 5.x, 6.x]
        env:
            WAIT_ON_TIMEOUT: 5000
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run --if-present build
            - name: Install Vite ${{ matrix.vite-version }}
              run: |
                  npm install $(npx -y npm-min-peer vite --major ${{ matrix.vite-version }} --with-name)
                  npm ls vite
            - name: Integration test (commonjs)
              run: npm run vite:cjs
            - name: Integration test (esm)
              run: npm run vite:mjs
